"""empty message

Revision ID: 52911c2c6be3
Revises: 190dd278aadf
Create Date: 2020-11-09 16:38:38.273876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52911c2c6be3'
down_revision = '190dd278aadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_een', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_een')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
